package com.family.child

import android.content.Context

/** Online-safety reminder shuffle bag. */
object WisdomStore {
    private const val PREFS = "online_safety_rotation_v3"
    private const val KEY_ORDER = "order"
    private const val KEY_POS = "position"
    private const val KEY_LAST = "last_index"
    private val lock = Any()

    fun next(context: Context): String = synchronized(lock) {
        val prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
        var order = prefs.getString(KEY_ORDER, null)?.split(',')?.mapNotNull { it.toIntOrNull() }?.filter { it in QUOTES.indices } ?: emptyList()
        var pos = prefs.getInt(KEY_POS, 0)
        val last = prefs.getInt(KEY_LAST, -1)
        if (order.size != QUOTES.size || order.toSet().size != QUOTES.size || pos !in 0 until QUOTES.size) { order = newOrder(last); pos = 0 }
        val index = order[pos]
        val nextPos = pos + 1
        val editor = prefs.edit().putInt(KEY_LAST, index)
        if (nextPos >= QUOTES.size) editor.remove(KEY_ORDER).putInt(KEY_POS, QUOTES.size)
        else editor.putString(KEY_ORDER, order.joinToString(",")).putInt(KEY_POS, nextPos)
        editor.apply()
        QUOTES[index]
    }

    fun count(): Int = QUOTES.size

    private fun newOrder(last: Int): List<Int> {
        val order = QUOTES.indices.shuffled().toMutableList()
        if (order.size > 1 && order.first() == last) {
            val swap = 1 + (System.nanoTime().toInt().and(Int.MAX_VALUE) % (order.size - 1))
            val t = order[0]; order[0] = order[swap]; order[swap] = t
        }
        return order
    }

    private val QUOTES = listOf(
        "Cảnh giác với người hỏi mã OTP. Không cung cấp OTP cho bất kỳ ai, kể cả người tự xưng là nhân viên ngân hàng.",
        "Nếu gặp người hỏi mã OTP, hãy dừng lại kiểm tra. Không cung cấp OTP cho bất kỳ ai, kể cả người tự xưng là nhân viên ngân hàng.",
        "Đừng vội tin người hỏi mã OTP. Không cung cấp OTP cho bất kỳ ai, kể cả người tự xưng là nhân viên ngân hàng.",
        "Gặp người hỏi mã OTP? Không cung cấp OTP cho bất kỳ ai, kể cả người tự xưng là nhân viên ngân hàng.",
        "Cảnh giác với người hỏi mật khẩu hoặc mã PIN. Không chia sẻ mật khẩu, mã PIN hay mã mở khóa điện thoại.",
        "Nếu gặp người hỏi mật khẩu hoặc mã PIN, hãy dừng lại kiểm tra. Không chia sẻ mật khẩu, mã PIN hay mã mở khóa điện thoại.",
        "Đừng vội tin người hỏi mật khẩu hoặc mã PIN. Không chia sẻ mật khẩu, mã PIN hay mã mở khóa điện thoại.",
        "Gặp người hỏi mật khẩu hoặc mã PIN? Không chia sẻ mật khẩu, mã PIN hay mã mở khóa điện thoại.",
        "Cảnh giác với người xin số CVV của thẻ. Không cung cấp CVV hoặc ảnh đầy đủ hai mặt thẻ ngân hàng.",
        "Nếu gặp người xin số CVV của thẻ, hãy dừng lại kiểm tra. Không cung cấp CVV hoặc ảnh đầy đủ hai mặt thẻ ngân hàng.",
        "Đừng vội tin người xin số CVV của thẻ. Không cung cấp CVV hoặc ảnh đầy đủ hai mặt thẻ ngân hàng.",
        "Gặp người xin số CVV của thẻ? Không cung cấp CVV hoặc ảnh đầy đủ hai mặt thẻ ngân hàng.",
        "Cảnh giác với link đăng nhập gửi qua SMS. Tự mở ứng dụng hoặc website chính thức thay vì bấm link lạ.",
        "Nếu gặp link đăng nhập gửi qua SMS, hãy dừng lại kiểm tra. Tự mở ứng dụng hoặc website chính thức thay vì bấm link lạ.",
        "Đừng vội tin link đăng nhập gửi qua SMS. Tự mở ứng dụng hoặc website chính thức thay vì bấm link lạ.",
        "Gặp link đăng nhập gửi qua SMS? Tự mở ứng dụng hoặc website chính thức thay vì bấm link lạ.",
        "Cảnh giác với link lạ trên Zalo hoặc Messenger. Kiểm tra người gửi bằng một kênh liên lạc khác trước khi mở.",
        "Nếu gặp link lạ trên Zalo hoặc Messenger, hãy dừng lại kiểm tra. Kiểm tra người gửi bằng một kênh liên lạc khác trước khi mở.",
        "Đừng vội tin link lạ trên Zalo hoặc Messenger. Kiểm tra người gửi bằng một kênh liên lạc khác trước khi mở.",
        "Gặp link lạ trên Zalo hoặc Messenger? Kiểm tra người gửi bằng một kênh liên lạc khác trước khi mở.",
        "Cảnh giác với mã QR không rõ nguồn gốc. Đọc kỹ màn hình trước khi quét hoặc xác nhận giao dịch QR.",
        "Nếu gặp mã QR không rõ nguồn gốc, hãy dừng lại kiểm tra. Đọc kỹ màn hình trước khi quét hoặc xác nhận giao dịch QR.",
        "Đừng vội tin mã QR không rõ nguồn gốc. Đọc kỹ màn hình trước khi quét hoặc xác nhận giao dịch QR.",
        "Gặp mã QR không rõ nguồn gốc? Đọc kỹ màn hình trước khi quét hoặc xác nhận giao dịch QR.",
        "Cảnh giác với file APK gửi ngoài cửa hàng ứng dụng. Không cài ứng dụng không rõ nguồn gốc.",
        "Nếu gặp file APK gửi ngoài cửa hàng ứng dụng, hãy dừng lại kiểm tra. Không cài ứng dụng không rõ nguồn gốc.",
        "Đừng vội tin file APK gửi ngoài cửa hàng ứng dụng. Không cài ứng dụng không rõ nguồn gốc.",
        "Gặp file APK gửi ngoài cửa hàng ứng dụng? Không cài ứng dụng không rõ nguồn gốc.",
        "Cảnh giác với ứng dụng lạ xin quyền Trợ năng. Không cấp quyền Trợ năng nếu bạn không hiểu rõ lý do.",
        "Nếu gặp ứng dụng lạ xin quyền Trợ năng, hãy dừng lại kiểm tra. Không cấp quyền Trợ năng nếu bạn không hiểu rõ lý do.",
        "Đừng vội tin ứng dụng lạ xin quyền Trợ năng. Không cấp quyền Trợ năng nếu bạn không hiểu rõ lý do.",
        "Gặp ứng dụng lạ xin quyền Trợ năng? Không cấp quyền Trợ năng nếu bạn không hiểu rõ lý do.",
        "Cảnh giác với ứng dụng lạ xin quyền đọc SMS. Chỉ cấp quyền thực sự cần thiết cho ứng dụng đáng tin cậy.",
        "Nếu gặp ứng dụng lạ xin quyền đọc SMS, hãy dừng lại kiểm tra. Chỉ cấp quyền thực sự cần thiết cho ứng dụng đáng tin cậy.",
        "Đừng vội tin ứng dụng lạ xin quyền đọc SMS. Chỉ cấp quyền thực sự cần thiết cho ứng dụng đáng tin cậy.",
        "Gặp ứng dụng lạ xin quyền đọc SMS? Chỉ cấp quyền thực sự cần thiết cho ứng dụng đáng tin cậy.",
        "Cảnh giác với người yêu cầu chia sẻ màn hình. Không chia sẻ màn hình khi đang mở ngân hàng hoặc ví điện tử.",
        "Nếu gặp người yêu cầu chia sẻ màn hình, hãy dừng lại kiểm tra. Không chia sẻ màn hình khi đang mở ngân hàng hoặc ví điện tử.",
        "Đừng vội tin người yêu cầu chia sẻ màn hình. Không chia sẻ màn hình khi đang mở ngân hàng hoặc ví điện tử.",
        "Gặp người yêu cầu chia sẻ màn hình? Không chia sẻ màn hình khi đang mở ngân hàng hoặc ví điện tử.",
        "Cảnh giác với người yêu cầu cài AnyDesk hoặc TeamViewer. Không cho người lạ điều khiển điện thoại từ xa.",
        "Nếu gặp người yêu cầu cài AnyDesk hoặc TeamViewer, hãy dừng lại kiểm tra. Không cho người lạ điều khiển điện thoại từ xa.",
        "Đừng vội tin người yêu cầu cài AnyDesk hoặc TeamViewer. Không cho người lạ điều khiển điện thoại từ xa.",
        "Gặp người yêu cầu cài AnyDesk hoặc TeamViewer? Không cho người lạ điều khiển điện thoại từ xa.",
        "Cảnh giác với cuộc gọi tự xưng công an. Công an không yêu cầu chuyển tiền vào tài khoản để xác minh.",
        "Nếu gặp cuộc gọi tự xưng công an, hãy dừng lại kiểm tra. Công an không yêu cầu chuyển tiền vào tài khoản để xác minh.",
        "Đừng vội tin cuộc gọi tự xưng công an. Công an không yêu cầu chuyển tiền vào tài khoản để xác minh.",
        "Gặp cuộc gọi tự xưng công an? Công an không yêu cầu chuyển tiền vào tài khoản để xác minh.",
        "Cảnh giác với cuộc gọi tự xưng tòa án hoặc viện kiểm sát. Ngắt cuộc gọi và tự liên hệ cơ quan qua số chính thức.",
        "Nếu gặp cuộc gọi tự xưng tòa án hoặc viện kiểm sát, hãy dừng lại kiểm tra. Ngắt cuộc gọi và tự liên hệ cơ quan qua số chính thức.",
        "Đừng vội tin cuộc gọi tự xưng tòa án hoặc viện kiểm sát. Ngắt cuộc gọi và tự liên hệ cơ quan qua số chính thức.",
        "Gặp cuộc gọi tự xưng tòa án hoặc viện kiểm sát? Ngắt cuộc gọi và tự liên hệ cơ quan qua số chính thức.",
        "Cảnh giác với người nói phải chuyển tiền vào tài khoản an toàn. Ngân hàng không yêu cầu chuyển toàn bộ tiền sang một tài khoản khác để bảo vệ.",
        "Nếu gặp người nói phải chuyển tiền vào tài khoản an toàn, hãy dừng lại kiểm tra. Ngân hàng không yêu cầu chuyển toàn bộ tiền sang một tài khoản khác để bảo vệ.",
        "Đừng vội tin người nói phải chuyển tiền vào tài khoản an toàn. Ngân hàng không yêu cầu chuyển toàn bộ tiền sang một tài khoản khác để bảo vệ.",
        "Gặp người nói phải chuyển tiền vào tài khoản an toàn? Ngân hàng không yêu cầu chuyển toàn bộ tiền sang một tài khoản khác để bảo vệ.",
        "Cảnh giác với cuộc gọi dọa tài khoản ngân hàng bị khóa. Tự mở ứng dụng ngân hàng hoặc gọi tổng đài chính thức để kiểm tra.",
        "Nếu gặp cuộc gọi dọa tài khoản ngân hàng bị khóa, hãy dừng lại kiểm tra. Tự mở ứng dụng ngân hàng hoặc gọi tổng đài chính thức để kiểm tra.",
        "Đừng vội tin cuộc gọi dọa tài khoản ngân hàng bị khóa. Tự mở ứng dụng ngân hàng hoặc gọi tổng đài chính thức để kiểm tra.",
        "Gặp cuộc gọi dọa tài khoản ngân hàng bị khóa? Tự mở ứng dụng ngân hàng hoặc gọi tổng đài chính thức để kiểm tra.",
        "Cảnh giác với người biết họ tên hoặc số CCCD của bạn. Biết thông tin cá nhân không chứng minh người gọi là cơ quan thật.",
        "Nếu gặp người biết họ tên hoặc số CCCD của bạn, hãy dừng lại kiểm tra. Biết thông tin cá nhân không chứng minh người gọi là cơ quan thật.",
        "Đừng vội tin người biết họ tên hoặc số CCCD của bạn. Biết thông tin cá nhân không chứng minh người gọi là cơ quan thật.",
        "Gặp người biết họ tên hoặc số CCCD của bạn? Biết thông tin cá nhân không chứng minh người gọi là cơ quan thật.",
        "Cảnh giác với người quen nhắn vay tiền gấp. Gọi trực tiếp cho người đó trước khi chuyển tiền.",
        "Nếu gặp người quen nhắn vay tiền gấp, hãy dừng lại kiểm tra. Gọi trực tiếp cho người đó trước khi chuyển tiền.",
        "Đừng vội tin người quen nhắn vay tiền gấp. Gọi trực tiếp cho người đó trước khi chuyển tiền.",
        "Gặp người quen nhắn vay tiền gấp? Gọi trực tiếp cho người đó trước khi chuyển tiền.",
        "Cảnh giác với người thân báo cấp cứu và cần tiền. Xác minh bằng số điện thoại quen thuộc hoặc hỏi một người thân khác.",
        "Nếu gặp người thân báo cấp cứu và cần tiền, hãy dừng lại kiểm tra. Xác minh bằng số điện thoại quen thuộc hoặc hỏi một người thân khác.",
        "Đừng vội tin người thân báo cấp cứu và cần tiền. Xác minh bằng số điện thoại quen thuộc hoặc hỏi một người thân khác.",
        "Gặp người thân báo cấp cứu và cần tiền? Xác minh bằng số điện thoại quen thuộc hoặc hỏi một người thân khác.",
        "Cảnh giác với giọng nói quen thuộc nhưng yêu cầu chuyển tiền. Giọng nói có thể bị giả bằng AI; hãy dùng câu hỏi riêng để xác minh.",
        "Nếu gặp giọng nói quen thuộc nhưng yêu cầu chuyển tiền, hãy dừng lại kiểm tra. Giọng nói có thể bị giả bằng AI; hãy dùng câu hỏi riêng để xác minh.",
        "Đừng vội tin giọng nói quen thuộc nhưng yêu cầu chuyển tiền. Giọng nói có thể bị giả bằng AI; hãy dùng câu hỏi riêng để xác minh.",
        "Gặp giọng nói quen thuộc nhưng yêu cầu chuyển tiền? Giọng nói có thể bị giả bằng AI; hãy dùng câu hỏi riêng để xác minh.",
        "Cảnh giác với video khuôn mặt quen thuộc yêu cầu tiền. Hình ảnh cũng có thể bị giả; hãy kiểm tra qua kênh khác.",
        "Nếu gặp video khuôn mặt quen thuộc yêu cầu tiền, hãy dừng lại kiểm tra. Hình ảnh cũng có thể bị giả; hãy kiểm tra qua kênh khác.",
        "Đừng vội tin video khuôn mặt quen thuộc yêu cầu tiền. Hình ảnh cũng có thể bị giả; hãy kiểm tra qua kênh khác.",
        "Gặp video khuôn mặt quen thuộc yêu cầu tiền? Hình ảnh cũng có thể bị giả; hãy kiểm tra qua kênh khác.",
        "Cảnh giác với tài khoản bạn bè gửi link bình chọn. Hỏi lại người bạn trước khi đăng nhập hoặc cung cấp mã xác thực.",
        "Nếu gặp tài khoản bạn bè gửi link bình chọn, hãy dừng lại kiểm tra. Hỏi lại người bạn trước khi đăng nhập hoặc cung cấp mã xác thực.",
        "Đừng vội tin tài khoản bạn bè gửi link bình chọn. Hỏi lại người bạn trước khi đăng nhập hoặc cung cấp mã xác thực.",
        "Gặp tài khoản bạn bè gửi link bình chọn? Hỏi lại người bạn trước khi đăng nhập hoặc cung cấp mã xác thực.",
        "Cảnh giác với người nhờ nhận hộ rồi chuyển tiếp tiền. Không dùng tài khoản của bạn để trung chuyển tiền không rõ nguồn gốc.",
        "Nếu gặp người nhờ nhận hộ rồi chuyển tiếp tiền, hãy dừng lại kiểm tra. Không dùng tài khoản của bạn để trung chuyển tiền không rõ nguồn gốc.",
        "Đừng vội tin người nhờ nhận hộ rồi chuyển tiếp tiền. Không dùng tài khoản của bạn để trung chuyển tiền không rõ nguồn gốc.",
        "Gặp người nhờ nhận hộ rồi chuyển tiếp tiền? Không dùng tài khoản của bạn để trung chuyển tiền không rõ nguồn gốc.",
        "Cảnh giác với đề nghị thuê tài khoản ngân hàng hoặc SIM. Không cho thuê hoặc cho mượn tài khoản tài chính và SIM.",
        "Nếu gặp đề nghị thuê tài khoản ngân hàng hoặc SIM, hãy dừng lại kiểm tra. Không cho thuê hoặc cho mượn tài khoản tài chính và SIM.",
        "Đừng vội tin đề nghị thuê tài khoản ngân hàng hoặc SIM. Không cho thuê hoặc cho mượn tài khoản tài chính và SIM.",
        "Gặp đề nghị thuê tài khoản ngân hàng hoặc SIM? Không cho thuê hoặc cho mượn tài khoản tài chính và SIM.",
        "Cảnh giác với shipper hỏi mã OTP ngân hàng. Shipper không cần OTP ngân hàng để giao hàng.",
        "Nếu gặp shipper hỏi mã OTP ngân hàng, hãy dừng lại kiểm tra. Shipper không cần OTP ngân hàng để giao hàng.",
        "Đừng vội tin shipper hỏi mã OTP ngân hàng. Shipper không cần OTP ngân hàng để giao hàng.",
        "Gặp shipper hỏi mã OTP ngân hàng? Shipper không cần OTP ngân hàng để giao hàng.",
        "Cảnh giác với shipper gửi QR để xác nhận đơn. Kiểm tra đơn trong ứng dụng mua sắm chính thức.",
        "Nếu gặp shipper gửi QR để xác nhận đơn, hãy dừng lại kiểm tra. Kiểm tra đơn trong ứng dụng mua sắm chính thức.",
        "Đừng vội tin shipper gửi QR để xác nhận đơn. Kiểm tra đơn trong ứng dụng mua sắm chính thức.",
        "Gặp shipper gửi QR để xác nhận đơn? Kiểm tra đơn trong ứng dụng mua sắm chính thức.",
        "Cảnh giác với người mua gửi link xác nhận nhận tiền. Nhận tiền không yêu cầu bạn đăng nhập qua link do người mua gửi.",
        "Nếu gặp người mua gửi link xác nhận nhận tiền, hãy dừng lại kiểm tra. Nhận tiền không yêu cầu bạn đăng nhập qua link do người mua gửi.",
        "Đừng vội tin người mua gửi link xác nhận nhận tiền. Nhận tiền không yêu cầu bạn đăng nhập qua link do người mua gửi.",
        "Gặp người mua gửi link xác nhận nhận tiền? Nhận tiền không yêu cầu bạn đăng nhập qua link do người mua gửi.",
        "Cảnh giác với ảnh chụp biên lai chuyển khoản. Kiểm tra số dư thực tế trong ứng dụng ngân hàng trước khi giao hàng.",
        "Nếu gặp ảnh chụp biên lai chuyển khoản, hãy dừng lại kiểm tra. Kiểm tra số dư thực tế trong ứng dụng ngân hàng trước khi giao hàng.",
        "Đừng vội tin ảnh chụp biên lai chuyển khoản. Kiểm tra số dư thực tế trong ứng dụng ngân hàng trước khi giao hàng.",
        "Gặp ảnh chụp biên lai chuyển khoản? Kiểm tra số dư thực tế trong ứng dụng ngân hàng trước khi giao hàng.",
        "Cảnh giác với shop yêu cầu thanh toán ngoài sàn. Ưu tiên kênh thanh toán chính thức để còn cơ chế bảo vệ giao dịch.",
        "Nếu gặp shop yêu cầu thanh toán ngoài sàn, hãy dừng lại kiểm tra. Ưu tiên kênh thanh toán chính thức để còn cơ chế bảo vệ giao dịch.",
        "Đừng vội tin shop yêu cầu thanh toán ngoài sàn. Ưu tiên kênh thanh toán chính thức để còn cơ chế bảo vệ giao dịch.",
        "Gặp shop yêu cầu thanh toán ngoài sàn? Ưu tiên kênh thanh toán chính thức để còn cơ chế bảo vệ giao dịch.",
        "Cảnh giác với món hàng rẻ bất thường. Giá quá tốt có thể là mồi nhử; hãy kiểm tra uy tín người bán.",
        "Nếu gặp món hàng rẻ bất thường, hãy dừng lại kiểm tra. Giá quá tốt có thể là mồi nhử; hãy kiểm tra uy tín người bán.",
        "Đừng vội tin món hàng rẻ bất thường. Giá quá tốt có thể là mồi nhử; hãy kiểm tra uy tín người bán.",
        "Gặp món hàng rẻ bất thường? Giá quá tốt có thể là mồi nhử; hãy kiểm tra uy tín người bán.",
        "Cảnh giác với việc nhẹ lương cao nhưng phải nạp tiền. Công việc thật không yêu cầu nạp tiền để được nhận lương.",
        "Nếu gặp việc nhẹ lương cao nhưng phải nạp tiền, hãy dừng lại kiểm tra. Công việc thật không yêu cầu nạp tiền để được nhận lương.",
        "Đừng vội tin việc nhẹ lương cao nhưng phải nạp tiền. Công việc thật không yêu cầu nạp tiền để được nhận lương.",
        "Gặp việc nhẹ lương cao nhưng phải nạp tiền? Công việc thật không yêu cầu nạp tiền để được nhận lương.",
        "Cảnh giác với nhiệm vụ online kiếm hoa hồng. Không nạp thêm tiền để mở khóa nhiệm vụ hoặc rút tiền.",
        "Nếu gặp nhiệm vụ online kiếm hoa hồng, hãy dừng lại kiểm tra. Không nạp thêm tiền để mở khóa nhiệm vụ hoặc rút tiền.",
        "Đừng vội tin nhiệm vụ online kiếm hoa hồng. Không nạp thêm tiền để mở khóa nhiệm vụ hoặc rút tiền.",
        "Gặp nhiệm vụ online kiếm hoa hồng? Không nạp thêm tiền để mở khóa nhiệm vụ hoặc rút tiền.",
        "Cảnh giác với cộng tác viên chốt đơn phải ứng tiền. Dừng lại nếu công việc bắt bạn ứng tiền trước.",
        "Nếu gặp cộng tác viên chốt đơn phải ứng tiền, hãy dừng lại kiểm tra. Dừng lại nếu công việc bắt bạn ứng tiền trước.",
        "Đừng vội tin cộng tác viên chốt đơn phải ứng tiền. Dừng lại nếu công việc bắt bạn ứng tiền trước.",
        "Gặp cộng tác viên chốt đơn phải ứng tiền? Dừng lại nếu công việc bắt bạn ứng tiền trước.",
        "Cảnh giác với nhà tuyển dụng chỉ nói chuyện qua Telegram. Xác minh công ty độc lập trước khi gửi giấy tờ hoặc tiền.",
        "Nếu gặp nhà tuyển dụng chỉ nói chuyện qua Telegram, hãy dừng lại kiểm tra. Xác minh công ty độc lập trước khi gửi giấy tờ hoặc tiền.",
        "Đừng vội tin nhà tuyển dụng chỉ nói chuyện qua Telegram. Xác minh công ty độc lập trước khi gửi giấy tờ hoặc tiền.",
        "Gặp nhà tuyển dụng chỉ nói chuyện qua Telegram? Xác minh công ty độc lập trước khi gửi giấy tờ hoặc tiền.",
        "Cảnh giác với chuyên gia hứa lấy lại tiền bị lừa. Không đóng phí trước cho người hứa thu hồi tiền.",
        "Nếu gặp chuyên gia hứa lấy lại tiền bị lừa, hãy dừng lại kiểm tra. Không đóng phí trước cho người hứa thu hồi tiền.",
        "Đừng vội tin chuyên gia hứa lấy lại tiền bị lừa. Không đóng phí trước cho người hứa thu hồi tiền.",
        "Gặp chuyên gia hứa lấy lại tiền bị lừa? Không đóng phí trước cho người hứa thu hồi tiền.",
        "Cảnh giác với đầu tư cam kết lợi nhuận cao không rủi ro. Không có đầu tư hợp pháp nào bảo đảm lợi nhuận cao tuyệt đối.",
        "Nếu gặp đầu tư cam kết lợi nhuận cao không rủi ro, hãy dừng lại kiểm tra. Không có đầu tư hợp pháp nào bảo đảm lợi nhuận cao tuyệt đối.",
        "Đừng vội tin đầu tư cam kết lợi nhuận cao không rủi ro. Không có đầu tư hợp pháp nào bảo đảm lợi nhuận cao tuyệt đối.",
        "Gặp đầu tư cam kết lợi nhuận cao không rủi ro? Không có đầu tư hợp pháp nào bảo đảm lợi nhuận cao tuyệt đối.",
        "Cảnh giác với sàn đầu tư chỉ hiển thị lợi nhuận trong app lạ. Số dư trên màn hình giả không chứng minh tiền thực sự tồn tại.",
        "Nếu gặp sàn đầu tư chỉ hiển thị lợi nhuận trong app lạ, hãy dừng lại kiểm tra. Số dư trên màn hình giả không chứng minh tiền thực sự tồn tại.",
        "Đừng vội tin sàn đầu tư chỉ hiển thị lợi nhuận trong app lạ. Số dư trên màn hình giả không chứng minh tiền thực sự tồn tại.",
        "Gặp sàn đầu tư chỉ hiển thị lợi nhuận trong app lạ? Số dư trên màn hình giả không chứng minh tiền thực sự tồn tại.",
        "Cảnh giác với sàn yêu cầu đóng thêm thuế mới cho rút tiền. Dừng chuyển tiền và xác minh nền tảng từ nguồn độc lập.",
        "Nếu gặp sàn yêu cầu đóng thêm thuế mới cho rút tiền, hãy dừng lại kiểm tra. Dừng chuyển tiền và xác minh nền tảng từ nguồn độc lập.",
        "Đừng vội tin sàn yêu cầu đóng thêm thuế mới cho rút tiền. Dừng chuyển tiền và xác minh nền tảng từ nguồn độc lập.",
        "Gặp sàn yêu cầu đóng thêm thuế mới cho rút tiền? Dừng chuyển tiền và xác minh nền tảng từ nguồn độc lập.",
        "Cảnh giác với nhóm kéo lệnh yêu cầu nạp tiền. Không đầu tư chỉ vì người trong nhóm khoe lợi nhuận.",
        "Nếu gặp nhóm kéo lệnh yêu cầu nạp tiền, hãy dừng lại kiểm tra. Không đầu tư chỉ vì người trong nhóm khoe lợi nhuận.",
        "Đừng vội tin nhóm kéo lệnh yêu cầu nạp tiền. Không đầu tư chỉ vì người trong nhóm khoe lợi nhuận.",
        "Gặp nhóm kéo lệnh yêu cầu nạp tiền? Không đầu tư chỉ vì người trong nhóm khoe lợi nhuận.",
        "Cảnh giác với người hỏi seed phrase ví tiền số. Không bao giờ chia sẻ seed phrase hoặc khóa riêng của ví.",
        "Nếu gặp người hỏi seed phrase ví tiền số, hãy dừng lại kiểm tra. Không bao giờ chia sẻ seed phrase hoặc khóa riêng của ví.",
        "Đừng vội tin người hỏi seed phrase ví tiền số. Không bao giờ chia sẻ seed phrase hoặc khóa riêng của ví.",
        "Gặp người hỏi seed phrase ví tiền số? Không bao giờ chia sẻ seed phrase hoặc khóa riêng của ví.",
        "Cảnh giác với quảng cáo đầu tư dùng người nổi tiếng. Video và giọng nói có thể bị giả bằng AI; hãy tự kiểm tra nguồn.",
        "Nếu gặp quảng cáo đầu tư dùng người nổi tiếng, hãy dừng lại kiểm tra. Video và giọng nói có thể bị giả bằng AI; hãy tự kiểm tra nguồn.",
        "Đừng vội tin quảng cáo đầu tư dùng người nổi tiếng. Video và giọng nói có thể bị giả bằng AI; hãy tự kiểm tra nguồn.",
        "Gặp quảng cáo đầu tư dùng người nổi tiếng? Video và giọng nói có thể bị giả bằng AI; hãy tự kiểm tra nguồn.",
        "Cảnh giác với thông báo trúng thưởng bất ngờ. Không đóng phí hoặc cung cấp OTP để nhận phần thưởng không rõ nguồn gốc.",
        "Nếu gặp thông báo trúng thưởng bất ngờ, hãy dừng lại kiểm tra. Không đóng phí hoặc cung cấp OTP để nhận phần thưởng không rõ nguồn gốc.",
        "Đừng vội tin thông báo trúng thưởng bất ngờ. Không đóng phí hoặc cung cấp OTP để nhận phần thưởng không rõ nguồn gốc.",
        "Gặp thông báo trúng thưởng bất ngờ? Không đóng phí hoặc cung cấp OTP để nhận phần thưởng không rõ nguồn gốc.",
        "Cảnh giác với quà miễn phí nhưng phải trả phí trước. Không chuyển tiền chỉ để mở khóa một món quà.",
        "Nếu gặp quà miễn phí nhưng phải trả phí trước, hãy dừng lại kiểm tra. Không chuyển tiền chỉ để mở khóa một món quà.",
        "Đừng vội tin quà miễn phí nhưng phải trả phí trước. Không chuyển tiền chỉ để mở khóa một món quà.",
        "Gặp quà miễn phí nhưng phải trả phí trước? Không chuyển tiền chỉ để mở khóa một món quà.",
        "Cảnh giác với cuộc gọi báo hoàn tiền. Nhận tiền không cần cung cấp mật khẩu, OTP hoặc CVV.",
        "Nếu gặp cuộc gọi báo hoàn tiền, hãy dừng lại kiểm tra. Nhận tiền không cần cung cấp mật khẩu, OTP hoặc CVV.",
        "Đừng vội tin cuộc gọi báo hoàn tiền. Nhận tiền không cần cung cấp mật khẩu, OTP hoặc CVV.",
        "Gặp cuộc gọi báo hoàn tiền? Nhận tiền không cần cung cấp mật khẩu, OTP hoặc CVV.",
        "Cảnh giác với QR được nói là để nhận tiền. Kiểm tra xem ứng dụng đang hiển thị nhận tiền hay thanh toán trước khi xác nhận.",
        "Nếu gặp QR được nói là để nhận tiền, hãy dừng lại kiểm tra. Kiểm tra xem ứng dụng đang hiển thị nhận tiền hay thanh toán trước khi xác nhận.",
        "Đừng vội tin QR được nói là để nhận tiền. Kiểm tra xem ứng dụng đang hiển thị nhận tiền hay thanh toán trước khi xác nhận.",
        "Gặp QR được nói là để nhận tiền? Kiểm tra xem ứng dụng đang hiển thị nhận tiền hay thanh toán trước khi xác nhận.",
        "Cảnh giác với người quen qua mạng gửi quà quốc tế. Không chuyển phí hải quan hoặc vận chuyển vào tài khoản cá nhân.",
        "Nếu gặp người quen qua mạng gửi quà quốc tế, hãy dừng lại kiểm tra. Không chuyển phí hải quan hoặc vận chuyển vào tài khoản cá nhân.",
        "Đừng vội tin người quen qua mạng gửi quà quốc tế. Không chuyển phí hải quan hoặc vận chuyển vào tài khoản cá nhân.",
        "Gặp người quen qua mạng gửi quà quốc tế? Không chuyển phí hải quan hoặc vận chuyển vào tài khoản cá nhân.",
        "Cảnh giác với người yêu qua mạng hỏi vay tiền. Xác minh danh tính rõ ràng và trao đổi với người thân trước khi chuyển.",
        "Nếu gặp người yêu qua mạng hỏi vay tiền, hãy dừng lại kiểm tra. Xác minh danh tính rõ ràng và trao đổi với người thân trước khi chuyển.",
        "Đừng vội tin người yêu qua mạng hỏi vay tiền. Xác minh danh tính rõ ràng và trao đổi với người thân trước khi chuyển.",
        "Gặp người yêu qua mạng hỏi vay tiền? Xác minh danh tính rõ ràng và trao đổi với người thân trước khi chuyển.",
        "Cảnh giác với người lạ xin ảnh nhạy cảm. Không gửi ảnh có thể bị dùng để tống tiền hoặc đe dọa.",
        "Nếu gặp người lạ xin ảnh nhạy cảm, hãy dừng lại kiểm tra. Không gửi ảnh có thể bị dùng để tống tiền hoặc đe dọa.",
        "Đừng vội tin người lạ xin ảnh nhạy cảm. Không gửi ảnh có thể bị dùng để tống tiền hoặc đe dọa.",
        "Gặp người lạ xin ảnh nhạy cảm? Không gửi ảnh có thể bị dùng để tống tiền hoặc đe dọa.",
        "Cảnh giác với người dọa phát tán ảnh để đòi tiền. Lưu bằng chứng và tìm người tin cậy hoặc cơ quan hỗ trợ; đừng tiếp tục trả tiền.",
        "Nếu gặp người dọa phát tán ảnh để đòi tiền, hãy dừng lại kiểm tra. Lưu bằng chứng và tìm người tin cậy hoặc cơ quan hỗ trợ; đừng tiếp tục trả tiền.",
        "Đừng vội tin người dọa phát tán ảnh để đòi tiền. Lưu bằng chứng và tìm người tin cậy hoặc cơ quan hỗ trợ; đừng tiếp tục trả tiền.",
        "Gặp người dọa phát tán ảnh để đòi tiền? Lưu bằng chứng và tìm người tin cậy hoặc cơ quan hỗ trợ; đừng tiếp tục trả tiền.",
        "Cảnh giác với người mới quen nhờ đầu tư vào sàn họ giới thiệu. Không gửi tiền chỉ dựa trên lòng tin trong một mối quan hệ online.",
        "Nếu gặp người mới quen nhờ đầu tư vào sàn họ giới thiệu, hãy dừng lại kiểm tra. Không gửi tiền chỉ dựa trên lòng tin trong một mối quan hệ online.",
        "Đừng vội tin người mới quen nhờ đầu tư vào sàn họ giới thiệu. Không gửi tiền chỉ dựa trên lòng tin trong một mối quan hệ online.",
        "Gặp người mới quen nhờ đầu tư vào sàn họ giới thiệu? Không gửi tiền chỉ dựa trên lòng tin trong một mối quan hệ online.",
        "Cảnh giác với người liên tục giục chuyển tiền ngay. Sự khẩn cấp là thủ thuật phổ biến; hãy dừng lại để kiểm tra.",
        "Nếu gặp người liên tục giục chuyển tiền ngay, hãy dừng lại kiểm tra. Sự khẩn cấp là thủ thuật phổ biến; hãy dừng lại để kiểm tra.",
        "Đừng vội tin người liên tục giục chuyển tiền ngay. Sự khẩn cấp là thủ thuật phổ biến; hãy dừng lại để kiểm tra.",
        "Gặp người liên tục giục chuyển tiền ngay? Sự khẩn cấp là thủ thuật phổ biến; hãy dừng lại để kiểm tra.",
        "Cảnh giác với yêu cầu giữ bí mật với gia đình. Một yêu cầu tài chính phải giữ bí mật là dấu hiệu nguy hiểm.",
        "Nếu gặp yêu cầu giữ bí mật với gia đình, hãy dừng lại kiểm tra. Một yêu cầu tài chính phải giữ bí mật là dấu hiệu nguy hiểm.",
        "Đừng vội tin yêu cầu giữ bí mật với gia đình. Một yêu cầu tài chính phải giữ bí mật là dấu hiệu nguy hiểm.",
        "Gặp yêu cầu giữ bí mật với gia đình? Một yêu cầu tài chính phải giữ bí mật là dấu hiệu nguy hiểm.",
        "Cảnh giác với tài khoản có nhiều người theo dõi hoặc dấu tích. Uy tín trên mạng có thể bị giả; hãy kiểm tra thông tin độc lập.",
        "Nếu gặp tài khoản có nhiều người theo dõi hoặc dấu tích, hãy dừng lại kiểm tra. Uy tín trên mạng có thể bị giả; hãy kiểm tra thông tin độc lập.",
        "Đừng vội tin tài khoản có nhiều người theo dõi hoặc dấu tích. Uy tín trên mạng có thể bị giả; hãy kiểm tra thông tin độc lập.",
        "Gặp tài khoản có nhiều người theo dõi hoặc dấu tích? Uy tín trên mạng có thể bị giả; hãy kiểm tra thông tin độc lập.",
        "Cảnh giác với ảnh hóa đơn hoặc giấy tờ gửi qua chat. Ảnh chụp có thể bị chỉnh sửa; đừng dùng nó làm bằng chứng duy nhất.",
        "Nếu gặp ảnh hóa đơn hoặc giấy tờ gửi qua chat, hãy dừng lại kiểm tra. Ảnh chụp có thể bị chỉnh sửa; đừng dùng nó làm bằng chứng duy nhất.",
        "Đừng vội tin ảnh hóa đơn hoặc giấy tờ gửi qua chat. Ảnh chụp có thể bị chỉnh sửa; đừng dùng nó làm bằng chứng duy nhất.",
        "Gặp ảnh hóa đơn hoặc giấy tờ gửi qua chat? Ảnh chụp có thể bị chỉnh sửa; đừng dùng nó làm bằng chứng duy nhất.",
        "Cảnh giác với người gọi giữ bạn trên điện thoại lúc chuyển tiền. Ngắt cuộc gọi rồi tự kiểm tra thông tin trước khi giao dịch.",
        "Nếu gặp người gọi giữ bạn trên điện thoại lúc chuyển tiền, hãy dừng lại kiểm tra. Ngắt cuộc gọi rồi tự kiểm tra thông tin trước khi giao dịch.",
        "Đừng vội tin người gọi giữ bạn trên điện thoại lúc chuyển tiền. Ngắt cuộc gọi rồi tự kiểm tra thông tin trước khi giao dịch.",
        "Gặp người gọi giữ bạn trên điện thoại lúc chuyển tiền? Ngắt cuộc gọi rồi tự kiểm tra thông tin trước khi giao dịch.",
        "Cảnh giác với tình huống khiến bạn thấy sợ hoặc quá hấp dẫn. Khi không chắc chắn, đừng chuyển tiền; hãy hỏi người thân trước.",
        "Nếu gặp tình huống khiến bạn thấy sợ hoặc quá hấp dẫn, hãy dừng lại kiểm tra. Khi không chắc chắn, đừng chuyển tiền; hãy hỏi người thân trước.",
        "Đừng vội tin tình huống khiến bạn thấy sợ hoặc quá hấp dẫn. Khi không chắc chắn, đừng chuyển tiền; hãy hỏi người thân trước.",
        "Gặp tình huống khiến bạn thấy sợ hoặc quá hấp dẫn? Khi không chắc chắn, đừng chuyển tiền; hãy hỏi người thân trước."
    )
}
